# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Course_Region\HMI_PyQt5_Course_Example\Qt_UI_Workspace\LCD_Counter_with_Two_Button\LCD_Counter_with_Two_Button.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.QLCD_Num_1 = QtWidgets.QLCDNumber(Form)
        self.QLCD_Num_1.setObjectName("QLCD_Num_1")
        self.verticalLayout.addWidget(self.QLCD_Num_1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.QPB_1 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.QPB_1.setFont(font)
        self.QPB_1.setObjectName("QPB_1")
        self.horizontalLayout.addWidget(self.QPB_1)
        self.QPB_2 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.QPB_2.setFont(font)
        self.QPB_2.setObjectName("QPB_2")
        self.horizontalLayout.addWidget(self.QPB_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "LCD Counter with Two Button"))
        self.QPB_1.setText(_translate("Form", "+1"))
        self.QPB_2.setText(_translate("Form", "-1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
